- name: bug
  color: "d73a4a"
  description: Reproducible defect in behavior.
- name: enhancement
  color: "a2eeef"
  description: Backward-compatible improvement request.
- name: documentation
  color: "0075ca"
  description: Documentation-only updates.
- name: good first issue
  color: "7057ff"
  description: Suitable for first-time contributors.
- name: help wanted
  color: "008672"
  description: Extra attention requested from contributors.
- name: breaking-change
  color: "b60205"
  description: Includes a breaking public API behavior change.
- name: security
  color: "5319e7"
  description: Security-related maintenance.
