name: Bug report
description: Report a reproducible bug in resolver/downloader behavior.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please provide reproducible details.
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 20.x
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps/code to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: diagnostics
    attributes:
      label: reasonCode / diagnostics output
      description: Paste resolver/downloader typed failure output.
